### ISSUE TITLE
Computation in Page 50 (Chapter 2.1.4)

### ISSUE THREAD

**Issue by Serious-Huang** [unpingco/Python-for-Probability-Statistics-and-Machine-Learning-2E#10]
Hi, I'm new in Github. I have a question about the computation in Page 50. I think it should be:
![image](https://user-images.githubusercontent.com/129483484/229035368-f4c53cb4-3516-4d87-8e9f-8ac1450c7e75.png)
Could you please check this computation?

**Comment by unpingco** [comment]
@Serious-Huang  I think you are correct. I'll have to fix this in the next edition! Thanks for the tip!
