### ISSUE TITLE
Third Edition of "Python for Probability, Statistics, and Machine Learning"

### ISSUE THREAD

**Issue by Chm88** [unpingco/Python-for-Probability-Statistics-and-Machine-Learning-2E#11]
Sorry, I haven't found the github page for the 3rd edition of your above-mentioned book. So I'm making here a comment on a typo in the 3rd edition.
On page of 48 of the 3rd edition, "Lesbesgue theory" should read "Lebesgue theory".

**Comment by unpingco** [comment]
Thanks! I'll fix it in the next edition.
