### ISSUE TITLE
Conditional_Expectation_Projection.ipynb

### ISSUE THREAD

**Issue by SantiDu** [unpingco/Python-for-Probability-Statistics-and-Machine-Learning-2E#2]
Señor Unpingco, it's really hard for me to understand the formula below the sentence: "The conditional expectation is the minimum mean squared error (MMSE) solution to the following problem...", if it's of the form $  \int_{R} (x-h(Y))^2 f_X(x) dx $ or $  \int_{R} (x-h(Y))^2 f_{X|Y}(x|y) dx  $, it's more clear. It would be very kind of you if you could elaborate more on the formula.

**Comment by unpingco** [comment]
Thanks for the feedback. It should be the following:

$$ \min_h \int_{\mathbb{R}^2} (x - h(y) )^2 f_{X,Y}(x,y) dx dy $$

The proof at the end should help.

8b63af1
