### ISSUE TITLE
Typo Page 59

### ISSUE THREAD

**Issue by RicLouRiv** [unpingco/Python-for-Probability-Statistics-and-Machine-Learning-2E#3]
Hello - I think in the minimization problem you formulate in the middle of the page, you ought to be integrating against a density — meaning, you ought to include an “f(x)” after the (x-h(y))^2 term.

**Comment by unpingco** [comment]
Yes. This was mentioned here before. I fixed it in the corresponding Jupyter notebook on this site. Thanks for the feedback!

**Comment by RicLouRiv** [comment]
Apologies - I didn’t see it in the issue list on GitHub.

**Comment by unpingco** [comment]
No problem. It was a comment about the previous version of the Jupyter Notebook, not the page number.
