### ISSUE TITLE
ch. 2.1.1 "understanding probability density"

### ISSUE THREAD

**Issue by CMoebus** [unpingco/Python-for-Probability-Statistics-and-Machine-Learning-2E#6]
Hi José, I am sympathetic with the idea to base the chapter two on measure theory and the Lebesgue integral. But the example on p.40 and Fig 2.4 are in contradiction to the chapter title. Fig 2.1 doesn't show a density. Areas don't add up to 1. Furthermore the two measures have the same length 1. This does not motivate a learner to invest time in learning Lebesgue integration. Instead the graphic in Fig 2.1 I find a graphic in the german Wikipedia (https://de.wikipedia.org/wiki/Lebesgue-Integral) more instructive. The density is bimodal and the measures have different sizes. So the German graphic is even better that one of the English Wikipedia.
What is also missing is a hint or an example why the Lebesgue integral is necessary for understanding the chapters to come.
A further bonus would be Python code doing Lebsgue integration with an example where Riemann integration is not possible.
All the best, Claus

**Comment by unpingco** [comment]
The German graphic is great. I agree with your comment and will try to get that in the next edition. Thanks for the great feedback. You may find _Jones, Frank. Lebesgue Integration on Euclidean Space_ a good reference because it is very accessible for measure theory topics.
