### ISSUE TITLE
computation in Page 49

### ISSUE THREAD

**Issue by ronaldpan** [unpingco/Python-for-Probability-Statistics-and-Machine-Learning-2E#7]
Could you please chech the computation in Page 49? I think it should be 
![image](https://user-images.githubusercontent.com/13417382/127239500-167f0dba-59c2-4066-8a21-4deaa04cf676.png)

**Comment by unpingco** [comment]
Yes. You are correct. The corresponding Jupyter notebook [here ](https://github.com/unpingco/Python-for-Probability-Statistics-and-Machine-Learning-2E/blob/master/chapter/probability/intro.ipynb) already has the correction.
