### ISSUE TITLE
Errors in 2.1.5 Independent Random Variables

### ISSUE THREAD

**Issue by ronaldpan** [unpingco/Python-for-Probability-Statistics-and-Machine-Learning-2E#8]
![image](https://user-images.githubusercontent.com/13417382/127814724-86605658-12d1-422f-a2bf-0468bf587b03.png)

**Comment by unpingco** [comment]
fixed [here](https://github.com/unpingco/Python-for-Probability-Statistics-and-Machine-Learning-2E/commit/36068db87bcddfc677fc478a10defbc8b5583ef2). Thanks!
