### ISSUE TITLE
sympy stats.sample API has changed

### ISSUE THREAD

**Issue by blueshrapnel** [unpingco/Python-for-Probability-Statistics-and-Machine-Learning-2E#9]
The return type of sample has been changed to return an iterator
object since version 1.7. For more information see
https://github.com/sympy/sympy/issues/19061

```python
import numpy as np
from sympy import stats
# Eq constrains Z
samples_z7 = lambda : stats.sample(x, S.Eq(z,7)) 
#using 6 as an estimate
mn= np.mean([(6-samples_z7())**2 for i in range(100)]) 
#7/2 is the MSE estimate
mn0= np.mean([(7/2.-samples_z7())**2 for i in range(100)]) 
print('MSE=%3.2f using 6 vs MSE=%3.2f using 7/2 ' % (mn,mn0))
```

Error message 
```python
----> 2 mn = np.mean([(6 - samples_z7())**2 for i in range(100)])
TypeError: unsupported operand type(s) for -: 'int' and 'generator'```

**Comment by unpingco** [comment]
I made the changes in the [sympy1.7 branch](https://github.com/unpingco/Python-for-Probability-Statistics-and-Machine-Learning-2E/tree/sympy1.7) because I did not want to conflict with the sympy version in the `environment.yml` specification. Hope that helps!
